### ISSUE TITLE
Can't update german bank list

### ISSUE THREAD

**Issue by talfari** [Project60/org.project60.bic#73]
AS mentioned in the title, I can't update the german bank list. 
The call allways times out, even if I increase the php timeout to 5 min.

I have a fresh install of civi (5.72.1) on an actual drupal instalaltion.

**Comment by bjendres** [comment]
Looks like the current source (``https://www.bundesbank.de/resource/blob/602630/1b5138f22cc648106b16a29ecc3117c1/mL/blz-aktuell-xls-data.xlsx``) does not exist any more, and redirects to an XML file. That means somebody will have to re-implement the parser for DE (Germany) with an XML reader.

**Comment by eptbertram** [comment]
I asked the German Bundesbank to re-publish the xlsx-file.

**Comment by eptbertram** [comment]
> I asked the German Bundesbank to re-publish the xlsx-file.

Antwort auf Ihre Anfrage 2024/010569 (16.7.24): 
[...], wir haben seit mehr als einem Jahr in unserem Newsletter zur Bankleitzahlendatei und auf unserer Internetseite darauf hingewiesen, dass es zum Gültigkeitstermin im März 2024 Änderungen in der Bereitstellung der Bankleitzahlendatei geben wird. 
Seit diesem Termin erfolgt die Bereitstellung – gepackt und ungepackt – in den Formaten **TXT, CSV** und XML. 

Diese Formate finden Sie zum Download unter folgendem Link: [Download – Bankleitzahlen | Deutsche Bundesbank](https://www.bundesbank.de/de/aufgaben/unbarer-zahlungsverkehr/serviceangebot/bankleitzahlen/download-bankleitzahlen-602592) 

Mit freundlichen Grüßen

Ihr Kommunikationsteam der 
Deutschen Bundesbank [...] 


It seems that _we_ have to update the url in the parser to https://www.bundesbank.de/resource/blob/926192/07561adcd024c5752c46afa317d554af/mL/blz-aktuell-csv-data.csv and change it from xlsx to csv.

**Comment by eptbertram** [comment]
Dear @bjendres , my college @epatietz implemented a new parser for German banks. It's working! Please feel free to accept the PR. 

@talfari You may replace the DE.php in your install with the new one. After that you should be able to update your BIC list again.

**Comment by bjendres** [comment]
I finally got around to test it, and I get the following error:
```
Warning: DOMDocument::loadHTML(): Tag nachfolgeblz invalid in Entity, line: 1 in PhpOffice\PhpSpreadsheet\Reader\Html->loadIntoExisting() (line 688 of /var/repositories/org.project60.bic/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Html.php)

#0 /var/www/civicrm_env/awo/drupal/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /var/repositories/org.project60.bic/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Html.php(688): DOMDocument->loadHTML()
#3 /var/repositories/org.project60.bic/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Html.php(212): PhpOffice\PhpSpreadsheet\Reader\Html->loadIntoExisting()
#4 /var/repositories/org.project60.bic/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/BaseReader.php(182): PhpOffice\PhpSpreadsheet\Reader\Html->loadSpreadsheetFromFile()
#5 /var/repositories/org.project60.bic/CRM/Bic/Parser/DE.php(53): PhpOffice\PhpSpreadsheet\Reader\BaseReader->load()
#6 /var/repositories/org.project60.bic/api/v3/Bic.php(165): CRM_Bic_Parser_DE->update()
#7 /var/www/civicrm_env/awo/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_bic_update()
```
Any ideas?

**Comment by peth-systopia** [comment]
> Any ideas?

I would like to add that we will likely need some funding for further work on this.

**Comment by bjendres** [comment]
> > Any ideas?

I would hope that @epatietz could have a look and fix it.

**Comment by bjendres** [comment]
> This seem to work just fine with `1.10.0`

However, depending on your PHP timeout, the process might be killed half way through. In this case, you can just hit the update button for each country again and again and see the number of BICs for the selected country go up. Once it doesn't go up any more, you should be done.
